name: Simple CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Basic Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create build directory
      run: mkdir -p dist
      
    - name: Copy files for build
      run: |
        cp index.html dist/
        cp style.css dist/
        cp script.js dist/
        
    - name: Validate HTML
      run: npx html-validate index.html || echo "HTML validation completed with warnings"
      
    - name: Basic security check
      run: npm audit --audit-level=high || echo "Security audit completed"
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: website-files
        path: dist/
        retention-days: 30
